version: '3'

services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: "Method(`GET`)"
      # Lowest possible priority: fallback route
      traefik.http.routers.whoami.priority: 1
    networks:
      traefik:

networks:
  traefik:
    name: traefik_proxy
