version: '3.4'
services:
  netbox:
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
    restart: always
    healthcheck:
      start_period: 300s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8080/api/ || exit 1"
    labels:
      traefik.enable: true
      traefik.http.services.netbox.loadbalancer.server.port: 8080
      #traefik.http.routers.netbox.rule: "Host(`netbox.example.com`)"
      traefik.http.routers.netbox.rule: "HostRegexp(`${COMPOSE_PROJECT_NAME}{trailer:[-.].*}`)"
    # The frontend must sit on both the traefik network and the application network
    networks:
      traefik:
        priority: 100
      default:
  netbox-worker:
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
    restart: always
  netbox-housekeeping:
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
    restart: always
  postgres:
    restart: always
  redis:
    restart: always
  redis-cache:
    restart: always

networks:
  default:
    #enable_ipv6: true
  traefik:
    name: traefik_proxy
