version: '3'

services:
  reverse-proxy:
    image: traefik:v2.9
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik

networks:
  default:
    name: traefik_proxy
